---
kind: pipeline
name: default

platform:
  os: osx
  arch: amd64

trigger:
  event:
  - push

steps:
- name: Hello world
  image: ubuntu
  commands:
  - echo Hello World!
  when:
    event:
      - push
---
kind: pipeline
name: deployment

platform:
  os: osx
  arch: amd64

trigger:
  event:
  - deployment

steps:
- name: Hello world
  image: ubuntu
  commands:
  - echo Hello World!
